### ISSUE TITLE
attend page cleanup

### ISSUE THREAD

**Issue by phette23** [code4lib/2017.code4lib.org#104]
Just a few things I've noticed, a lot of people are about to hit this page:

- [x] PR #103 fixes a missing period & the election URL results
- [x] "Only the top ten (highlighted) have been accepted so far" how are the proposals highlighted? I didn't notice any indicator
- [ ] would be nice to colorize the lanyard colors (red, yellow, green)
- [ ] can we link up something in the Hotel Fees section such as the housing link that's in the registration form?

**Comment by queryluke** [comment]
RE: second bullet, should it link to the accepted talks? Is this list valid?
http://2017.code4lib.org/talks/

**Comment by phette23** [comment]
Hmm that's a good question. Sentence says top 10 but that's more than ten listed. A question for people in Slack maybe? It seemed deliberate that the link was to the election results.

**Comment by queryluke** [comment]
Ah, context is important. Good point. I'm guessing just need to remove the "highlighted part"

**Comment by gmcharlt** [comment]
That it links to the election results is just an accident of timing, as /schedule/ was not ready when I initially updated /attend/. I think that item can now be adjusted to say something along the lines of "The schedule is available" and link to /schedule/.

**Comment by highermath** [comment]
http://2017.code4lib.org/talks/ looks correct. We should just kill the highlighted part. I would do it, but jekyll died on my workstation.

**Comment by queryluke** [comment]
I'm on it

**Comment by gmcharlt** [comment]
Yeah, /talks/ is more concise for the purpose than /schedule/.

**Comment by phette23** [comment]
I think the attend page looks fine these days, closing this just so there's less noise in the issues.
