### ISSUE TITLE
make revisions to the prospectus

### ISSUE THREAD

**Issue by joshuago78** [code4lib/2017.code4lib.org#14]
- Working document can be found here: https://docs.google.com/document/d/195m1tGq1y_Mkrr0UpEz8Hdge0vqknRSETqvZhhxtd2k/edit
- It is almost ready to go. They have a couple decisions to make regarding:
  - The number of table sponsorships (dependent on floor plan of the venue)
  - The number and dollar amount of the main reception sponsorships

**Comment by gmcharlt** [comment]
I've built on @jcoyne's patch and have opened a pull request for the final draft of the prospectus.
