### ISSUE TITLE
Add anti-harassment help info

### ISSUE THREAD

**Issue by joshuago78** [code4lib/2017.code4lib.org#158]
To be consistent with an upcoming merge to the code4lib anti-harassment policy, we need to add the following information to the website:

- Conference organizer name & phone number (Should this be Gary? Concentra?)
- Luskin Center phone number
- Los Angeles Police Department phone number
- Local sexual assault/crisis phone number
- Local taxi company name and phone number
- code4lib IRC Channel administrators usernames

**Comment by gmcharlt** [comment]
I'm working with Gary to help gather this information, and will update as it becomes available.

**Comment by gmcharlt** [comment]
There are a few placeholders to fill in, but I've got most of the information compiled here:

https://docs.google.com/document/d/12eM2HN2LKjA4uZdXfrdD_wqu3y6iNejwal5ZMFvKHxU/edit#

I'd like to ask advice on how best to structure this for the website: while some of the contact information is relevant to the code of conduct and can go on the code of conduct page or the duty officers page, some of it would be useful for any attendee who might find themselves in a fix that doesn't involve the code of conduct.

Would it make sense to refactor the 'Attend' page into a general resource page for attendees? Or add another page?

**Comment by joshuago78** [comment]
Yes there are a couple of information architecture changes that should be made to the site. I encountered a similar problem with activities/venues.

I think we can address this current issue by removing "Conduct" from the top level menu and in its place we put "Safety" which includes both "Conduct" and "Contact". 

Is there are policy that requires Conduct to be at the top level?

**Comment by gmcharlt** [comment]
I don't think there's anything mandating that Conduct be a top-level menu, although I do think that the code of conduct should be prominently linked. I'm +1 for changing the "Conduct" link in the header to a menu titled "Safety"; that menu could also contain a direct link to the Duty Officers page. (As a side note, I'm also gathering together photos of the safety officers, and Becky and I are working to get the schedule put together).

**Comment by phette23** [comment]
As an aside about information architecture, we've been continually adding pages to the site and links to the main menu while never subtracting anything. The site's gained some noticeable sprawl as a result. It'd be great to be able to pare back, maybe identify information that can live on the wiki or pages that can be combined (e.g. all the venues living on one page diving up into sections?).
