### ISSUE TITLE
link to transcription service should be added to website

### ISSUE THREAD

**Issue by gmcharlt** [code4lib/2017.code4lib.org#192]
https://2020captioning.1capapp.com/event/code4lib/

Note that somebody watching both the video stream and the captioning will need to have both windows open

**Comment by phette23** [comment]
I think #193 addressed this? Take a look at attend > accessibility & close if that's sufficient.

**Comment by gmcharlt** [comment]
I think it gets us 95% of the way — the only addition I would suggest is that when we put a link to the streaming video on the home page (see #191), it should be accompanied by the link to the transcription service, as somebody who wants captions when viewing the streaming will need to open it in a second window.
