### ISSUE TITLE
site.data.conf.toggles should be booleans

### ISSUE THREAD

**Issue by phette23** [code4lib/2017.code4lib.org#20]
Is there a reason the toggles in the conf.yml file are on/off strings & not booleans? See:

https://github.com/code4lib/2017.code4lib.org/blob/master/_data/conf.yml#L7-L16

I'd say `search: true` etc. is better. The conditionals all over the place like `{% if site.data.conf.toggles.livestream == "on" %}` seem a bit more verbose & error prone (e.g. `== "On"` will be false) than just  `{% if site.data.conf.toggles.livestream %}`. If we do change this the conditions _everywhere_ need to be updated which is actually a good reason to just keep it the way it is now.

**Comment by queryluke** [comment]
@phette23 Would you accept "my stupidity" as an acceptable answer? 😝 

In all honestly, I think I had my JSON hat on, not my YAML hat

I can go through and fix all of these, since I set them up.
