### ISSUE TITLE
Add conference proposal dates

### ISSUE THREAD

**Issue by scholarworks** [code4lib/2017.code4lib.org#21]
http://2017.code4lib.org/schedule/timeline.html

Call for Conference Proposals: 10/13 – 11/7 (presentation link: https://goo.gl/forms/GbM0jmSdXFkRdHAr2, panel link: https://goo.gl/forms/q2KbVcO4ntkh6bPp1)

Vote for Conference Proposals: 11/16 – 12/7 (link coming)

**Comment by phette23** [comment]
I'm working on this in #18 & just sent a PR so please wait for that.

**Comment by jcoyne** [comment]
@phette23 okay, unassigned myself.

**Comment by phette23** [comment]
Closing this as I think it's been addressed, please reopen if I'm mistaken. We'll need to add the conference proposal voting link later obviously but that's a ways off at the moment.
