### ISSUE TITLE
missing speaker

### ISSUE THREAD

**Issue by joshuago78** [code4lib/2017.code4lib.org#221]
This talk has no speaker: http://2017.code4lib.org/talks/Every-Library-is-a-Technology-Organization-Bringing-DevOps-principles-to-libraries

**Comment by gmcharlt** [comment]
Fell off during the speaker sorting. Now checking to see if this was the only case.

**Comment by gmcharlt** [comment]
Also lost jordan-nielsen and margaret-heller. Working on fix.
