### ISSUE TITLE
set root of the master branch to be GitHub Pages source

### ISSUE THREAD

**Issue by phette23** [code4lib/2017.code4lib.org#3]
https://github.com/blog/2228-simpler-github-pages-publishing

I think this just makes more sense & simplifies things, since this repo is entirely a GitHub Pages site & we can do the more traditional "push to feature branch, merge to master" workflow.

**Comment by queryluke** [comment]
@phette23 sounds like a great idea. One of the pain points last year was the workflow for:
- push branch change
- merge to master
- check
- merge to gh pages locally
- check
- merge master to gh pages

Sounds like this would be much easier

**Comment by phette23** [comment]
sweet, I've made this change, we can always switch back if we decide otherwise
