### ISSUE TITLE
Link color needs better contrast.

### ISSUE THREAD

**Issue by sdellis** [code4lib/2017.code4lib.org#41]
Currently, it's nearly impossible to tell what's a link or not.

**Comment by queryluke** [comment]
about to push a change for this. Using $accent as the link color, tired $accent-light but it doesn't pass contrast accessibility standards on the white background.

For thoroughness's sake, darker background ($primary-light, #d4d8d1), $accent will work for large text (i.e., the quote links on the home page). But not smaller text, so we'll just need to be cognizant when using $primary-light as a background color. For example, I switched the speaker info background to #eeeeee which passes.
