### ISSUE TITLE
Poor color contrast in links in photo on main page

### ISSUE THREAD

**Issue by metageeky** [code4lib/2017.code4lib.org#77]
There's a major accessibility issue with the links for voting, etc. on the index page within the photo. The color contrast needs to be made better. I couldn't even see them until I moused over them. Hover color too needs to be changed.

**Comment by metageeky** [comment]
I'm on it, just wanted to put this in officially.

**Comment by phette23** [comment]
I'm assuming we can close this because of the prior commit? Reopen if I'm wrong.
