### ISSUE TITLE
site.data.path references are broken in some places

### ISSUE THREAD

**Issue by phette23** [code4lib/2017.code4lib.org#9]
It looks like in the cleanup work the entirely of the _data/path.yml file was wiped out—it now contains just a single reference to the site root `'/'`. That actually works a lot of places but I noticed it broke some footer links:

``` html
<li class="list-item tci"><a href="{{ site.data.path }}schedule">Schedule</a></li>
<li class="list-item tci"><a href="{{ site.data.path }}attend.html">Attend</a></li>
```

in this instance, the "Schedule" link is fine since it gets redirected to the directory index but "attend.html" doesn't exist anymore and breaks. I'll send a PR referencing this & fixing the footer links but I wanted to point out the larger issue because ``{{site.data.path}}` references are littered throughout the code base and probably nonfunctional in a some other places.

**Comment by queryluke** [comment]
@phette23 If we're always going to have an updated cname, there is no reason to keep `{{site.data.path}}`, it was a stop-gap while we didn't have the 2016 subdomain last year

Clear it out or fix the broken ones?

**Comment by phette23** [comment]
I think it's a straight search-and-replace with "/" so I'd vote to clear out just to simplify things that minimal amount. I'm happy to do it.

**Comment by queryluke** [comment]
I'm for it 👍
